
package co.edu.utp.misiontic2022.c2.reto5.vista;

import co.edu.utp.misiontic2022.c2.reto5.controlador.ModeloControlador;

public class FrmPrincipal extends javax.swing.JFrame {

    
    private ModeloControlador modelo = new ModeloControlador();
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel = new javax.swing.JPanel();
        btnInformeProyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();
        btnInformeLider = new javax.swing.JButton();
        btnInformeCompra = new javax.swing.JButton();
        btnLimpiarTabla = new javax.swing.JButton();
        etiquetaInforme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jTabbedPane1.setForeground(new java.awt.Color(51, 102, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        btnInformeProyecto.setText("Segundo Informe  - Proyectos");
        btnInformeProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeProyectoActionPerformed(evt);
            }
        });

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaInforme);

        btnInformeLider.setText("Primer Informe - Lideres");
        btnInformeLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeLiderActionPerformed(evt);
            }
        });

        btnInformeCompra.setText("Tercer Informe  - Compras realizadas");
        btnInformeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeCompraActionPerformed(evt);
            }
        });

        btnLimpiarTabla.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiarTabla.setFont(new java.awt.Font("Garamond", 3, 18)); // NOI18N
        btnLimpiarTabla.setForeground(new java.awt.Color(51, 51, 255));
        btnLimpiarTabla.setText("Limpiar Tabla");
        btnLimpiarTabla.setEnabled(false);
        btnLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaActionPerformed(evt);
            }
        });

        etiquetaInforme.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        etiquetaInforme.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLimpiarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(etiquetaInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnInformeLider, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInformeProyecto)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformeCompra)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformeLider)
                    .addComponent(btnInformeProyecto)
                    .addComponent(btnInformeCompra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarTabla)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnLimpiarTabla.getAccessibleContext().setAccessibleName("Limpiar  tabla");

        jTabbedPane1.addTab("Reto 5  - Aplicación de escritorio para la extracción  de información y la generación de informes", panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformeProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeProyectoActionPerformed
        // TODO add your handling code here:
        tablaInforme.setModel(modelo.modeloTablaProyectos());
        etiquetaInforme.setText("Informe basándose en la información de los proyectos"
                + " cuya clasificación sea Casa Campestre");
        activarBotonVaciarRegistro(true);
    }//GEN-LAST:event_btnInformeProyectoActionPerformed

    private void btnInformeLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeLiderActionPerformed
        // TODO add your handling code here:
        tablaInforme.setModel(modelo.modeloTablaLideres());
        etiquetaInforme.setText("Informe con la información respectiva al Líder");
        activarBotonVaciarRegistro(true);
        
        
    }//GEN-LAST:event_btnInformeLiderActionPerformed

    private void btnInformeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeCompraActionPerformed
        // TODO add your handling code here:
        tablaInforme.setModel(modelo.modeloTablaCompras());
        etiquetaInforme.setText("Informe basándose en las compras realizadas por los proyectos con el proveedor Homecenter"
                + " y para la ciudad Salento");
        activarBotonVaciarRegistro(true);
    }//GEN-LAST:event_btnInformeCompraActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        // TODO add your handling code here:
        limpiarModeloTabla();
        etiquetaInforme.setText("");
        activarBotonVaciarRegistro(false);
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformeCompra;
    private javax.swing.JButton btnInformeLider;
    private javax.swing.JButton btnInformeProyecto;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JLabel etiquetaInforme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables
    
    // Método para activar y desactivar el boton vaciar tabla
    private void activarBotonVaciarRegistro(boolean flag){
        if (flag) {
            btnLimpiarTabla.setEnabled(flag);
        } else {
            btnLimpiarTabla.setEnabled(flag);
        }
    }
    
    // Método para vaciar los registros del modelo la tabla
    private void limpiarModeloTabla(){
        modelo.getModeloTabla().setColumnCount(0);
        modelo.getModeloTabla().setRowCount(0);
    }
}
